language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: COMPILER=clang++-3.9
before_install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libc++-dev
script:
  - ls /usr/include/c++/v1/experimental
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j4
  - ctest -V
