language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: COMPILER=clang++-4.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
  - sudo apt-get install libc++-dev libc++abi-dev
  - dpkg --search libc++ > test1
  - cat test1
  - wget http://launchpadlibrarian.net/331689507/libc++1_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689503/libc++-dev_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689511/libc++abi1_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689509/libc++abi-dev_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++1_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++-dev_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++abi1_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++abi-dev_3.9.1-3_amd64.deb
  - dpkg --search libc++ > test2
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libc++experimental.a /usr/lib/libstdc++fs.a
  - cat test2
script:
  - ls /usr/include/c++/v1/experimental
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j4
  - ctest -V
