sudo: required
dist: trusty
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
      env: COMPILER=clang++-3.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j4
  - ctest -V
