language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-6
            - clang-4.0
      env: COMPILER=clang++-4.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
  - sudo apt-get install clang-3.9
  - sudo apt-get install libc++-dev libc++abi-dev
script:
  - ls /usr/include/c++/v1/experimental
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j4
  - ctest -V
