language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: COMPILER=clang++-4.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc++-dev libc++abi-dev
  - dpkg --search libc++ > test1
  - cat test1
  - wget http://launchpadlibrarian.net/331689507/libc++1_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689503/libc++-dev_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689511/libc++abi1_3.9.1-3_amd64.deb
  - wget http://launchpadlibrarian.net/331689509/libc++abi-dev_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++1_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++-dev_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++abi1_3.9.1-3_amd64.deb
  - sudo dpkg -i libc++abi-dev_3.9.1-3_amd64.deb
  - dpkg --search libc++ > test2
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libc++experimental.a /usr/lib/libstdc++fs.a
  - cat test2
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository ppa:samuel-bachmann/boost -y; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install boost1.60; fi
  - if [ "$CXX" == "clang++" ]; then sudo wget -O boost_1_57_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz/download; fi
  - if [ "$CXX" == "clang++" ]; then sudo tar xzf boost_1_57_0.tar.gz; fi
  - if [ "$CXX" == "clang++" ]; then sudo cd boost_1_57_0/; fi
  - if [ "$CXX" == "clang++" ]; then clang++ --version; fi
  - if [ "$CXX" == "clang++" ]; then sudo ./bootstrap.sh --with-toolset=clang --with-icu=/usr/include/x86_64-linux-gnu --with-libraries=serialization,filesystem,system; fi
  - if [ "$CXX" == "clang++" ]; then cat ./bootstrap.log; fi
  - if [ "$CXX" == "clang++" ]; then sudo ./b2 toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" link=static threading=multi variant=release; fi
  - if [ "$CXX" == "clang++" ]; then sudo ./b2 install; fi
  - if [ "$CXX" == "clang++" ]; then cd ../; fi
script:
  - ls /usr/include/c++/v1/experimental
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j4
  - ctest -V
