# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://agehama.github.io/Pita/"

# Site title
title = "Pita デザインのためのプログラミング言語"
theme = "hugo-theme-learn"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

# Copyright
copyright = "(c) 2018 agehama."

# Language
languageCode = "ja-JP"
defaultContentLanguage = "ja"

[Languages]
[Languages.ja]
title = "Documentation for Pita"
weight = 1
languageName = "Japanese"

[[Languages.ja.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/agehama/Pita"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> License"
url = "/license"
weight = 30