name: PitaTest

on: push

jobs:
  build_pita:

    runs-on: ubuntu-latest

    steps:
    - name: setup
      run: |
        sudo apt update -qq
        sudo apt install clang make cmake libboost-dev
        uname -a
        pwd
        clang++ -v
        ls -la
